<a href="https://colab.research.google.com/github/fredprada/Python_for_Data_Science_and_AI_COURSE/blob/main/13_Two_Dimensional_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#How to transform lists on a matrix
import numpy as np
a=[[11,12,13],[21,22,23],[31,32,33]]
A=np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
#How to get the "level" or the dimension of the matrix 
#(returns the number of axis)
#(returns the number of nested lists)
a=[[11,12,13],[21,22,23],[31,32,33]]
A=np.array(a)
A.ndim

2

In [ ]:
#returns the shape of the matrix (lines, columns)
a=[[11,12,13],[21,22,23],[31,32,33]]
A=np.array(a)
A.shape

(3, 3)

In [ ]:
#returns the size of the matrix (lines x columns)
a=[[11,12,13],[21,22,23],[31,32,33]]
A=np.array(a)
A.size

9

In [ ]:
#positions of values within the matrix
a=[[11,12,13],[21,22,23],[31,32,33]]
A=np.array(a)
print(A)
A[1][2]
A[1,2]
#here it searches for the number on the SECOND row (described as 1) and the
#THIRD column (described as 2), therefore, we search for the number 23

[[11 12 13]
 [21 22 23]
 [31 32 33]]


23

In [ ]:
#positions of values within the matrix
a=[[11,12,13],[21,22,23],[31,32,33]]
A=np.array(a)
print(A)
A[1][2]
A[0:2,2]

[[11 12 13]
 [21 22 23]
 [31 32 33]]


array([13, 23])

In [ ]:
#Summing a numpy array sums up all the elements
a=np.array([[11,12,13],[21,22,23],[31,32,33]])
b=np.array([[11,12,13],[21,22,23],[31,32,33]])
a+b

array([[22, 24, 26],
       [42, 44, 46],
       [62, 64, 66]])

In [ ]:
#multiplication of matrices by a scalar
a=np.array([[11,12,13],[21,22,23],[31,32,33]])
a*2


array([[22, 24, 26],
       [42, 44, 46],
       [62, 64, 66]])

In [ ]:
#Hadamard product (multiply elements on the same location)
a=np.array([[11,12,13],[21,22,23],[31,32,33]])
b=np.array([[11,12,13],[21,22,23],[31,32,33]])
z=a*b
z


array([[ 121,  144,  169],
       [ 441,  484,  529],
       [ 961, 1024, 1089]])

In [ ]:
#matrix multiplication
#number of columns of one matrix must be the same as the number
#of rows of the other matrix
a=np.array([[0,1,1],[1,0,1]])
b=np.array([[1,1],[1,1],[-1,1]])
c=np.dot(a,b)
c

array([[0, 2],
       [0, 2]])

# Exercícios

In [ ]:
X=np.array([[1,0],[0,1]])
Y=np.array([[0,1],[1,0]])
Z=X+Y
Z

array([[1, 1],
       [1, 1]])

In [ ]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0:2,2]
out

array([1, 2])

In [ ]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)
Z

array([[2, 2],
       [2, 2]])